FROM python:3.10

WORKDIR /app

ENV FLASK_APP=main.py

ENV FLASK_ENV=development

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY ./ ./

EXPOSE 5000

# CMD [ "flask", "run", "--host=0.0.0.0", "--port=5000"]

# CMD ["python", "main.py", "--host=0.0.0.0", "--port=5000"]

CMD ["python", "main.py"]

# CMD ["python", "backend.main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]